imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - bootstrap_3_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

old_sound_rabbit_mq:
    connections:
        default:
            host:     "%rabbit_mq_host%"
            port:     "%rabbit_mq_port%"
            user:     "%rabbit_mq_user%"
            password: "%rabbit_mq_password%"
            vhost:    "%rabbit_mq_vhost%"
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3
    producers:
        hello:
            connection:       default
            queue_options:    {name: 'hello'}
        work:
            connection:       default
            queue_options:    {name: 'work'}
        logs:
            connection:       default
            exchange_options: {name: 'logs_ex', type: fanout}
        direct_logs:
            connection:       default
            exchange_options: {name: 'direct_ex', type: direct}
        topic_logs:
            connection:       default
            exchange_options: {name: 'topic_ex', type: topic}
    consumers:
        hello:
            connection:       default
            queue_options:    {name: 'hello'}
            callback:         AppBundle\Consumers\HelloConsumer
        work:
            connection:       default
            queue_options:    {name: 'work'}
            callback:         AppBundle\Consumers\WorkConsumer
            qos_options:      {prefetch_size: 0, prefetch_count: 1, global: false}
    anon_consumers:
        logs:
            connection:       default
            exchange_options: {name: 'logs_ex', type: fanout}
            callback:         AppBundle\Consumers\LogsConsumer
        direct_logs:
            connection:       default
            exchange_options: {name: 'direct_ex', type: direct}
            callback:         AppBundle\Consumers\DirectLogsConsumer
        topic_logs:
            connection:       default
            exchange_options: {name: 'topic_ex', type: topic}
            callback:         AppBundle\Consumers\TopicLogsConsumer
    rpc_clients:
        parse_url:
            connection: default
            unserializer: json_decode
            lazy: true
            direct_reply_to: false
    rpc_servers:
        parse_url:
            connection: default
            callback:   AppBundle\Service\ParseUrlServerService
            qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}
            exchange_options: {name: parse_url, type: direct}
            queue_options: {name: parse_url_queue, durable: false, auto_delete: true}
            serializer: json_encode